//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.FormFrw {
    
    
    public partial class FrmFrwActivityLogView {
        
        /// <summary>
        /// KPGridControlFrwActivityLog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPGridControl KPGridControlFrwActivityLog;
        
        /// <summary>
        /// ActionVisualize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPViewButtonSimple ActionVisualize;
    }
}
