//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.FormFrw {
    
    
    public partial class FrmFrwUserProfile {
        
        /// <summary>
        /// formControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormControl formControl;
        
        /// <summary>
        /// objIdUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemZoom objIdUser;
        
        /// <summary>
        /// BtnAddUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemButton BtnAddUsuario;
        
        /// <summary>
        /// grid_UsuarioEmpresa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemGrid grid_UsuarioEmpresa;
        
        /// <summary>
        /// UsuarioEmpresa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormGridModel UsuarioEmpresa;
    }
}
