//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject {
    
    
    public partial class FrmFrwProfileWindow {
        
        /// <summary>
        /// formControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormControl formControl;
        
        /// <summary>
        /// objIdWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemZoom objIdWindow;
        
        /// <summary>
        /// IsPreview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemCheckBox IsPreview;
        
        /// <summary>
        /// IsReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemCheckBox IsReadOnly;
        
        /// <summary>
        /// BtnAddWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemButton BtnAddWindow;
        
        /// <summary>
        /// GridUsuarioEmpresa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormItemGrid GridUsuarioEmpresa;
        
        /// <summary>
        /// PerfilTela control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KPComponents.KPFormGridModel PerfilTela;
    }
}
