//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProject.Properties.GlobalizationResource", typeof(GlobalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5W2H.
        /// </summary>
        internal static string Aba_5W2H {
            get {
                return ResourceManager.GetString("Aba_5W2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos.
        /// </summary>
        internal static string Aba_Contatos {
            get {
                return ResourceManager.GetString("Aba_Contatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações base.
        /// </summary>
        internal static string Aba_InformacoesBase {
            get {
                return ResourceManager.GetString("Aba_InformacoesBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações do Problema.
        /// </summary>
        internal static string Aba_InformacoesProblema {
            get {
                return ResourceManager.GetString("Aba_InformacoesProblema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta de Solução.
        /// </summary>
        internal static string Aba_MetaSolucao {
            get {
                return ResourceManager.GetString("Aba_MetaSolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string Aba_Observacoes {
            get {
                return ResourceManager.GetString("Aba_Observacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        internal static string Aba_Outros {
            get {
                return ResourceManager.GetString("Aba_Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano.
        /// </summary>
        internal static string Aba_Plano {
            get {
                return ResourceManager.GetString("Aba_Plano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string Aba_Principal {
            get {
                return ResourceManager.GetString("Aba_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci a senha.
        /// </summary>
        internal static string Application_ForgotPassword {
            get {
                return ResourceManager.GetString("Application_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso ao sistema.
        /// </summary>
        internal static string Application_LoginAccess {
            get {
                return ResourceManager.GetString("Application_LoginAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos abaixo para acessar o sistema..
        /// </summary>
        internal static string Application_LoginFillFields {
            get {
                return ResourceManager.GetString("Application_LoginFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro no sistema.
        /// </summary>
        internal static string Application_MessageError {
            get {
                return ResourceManager.GetString("Application_MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Platanum.
        /// </summary>
        internal static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar planejamento.
        /// </summary>
        internal static string Btn_ClosePlan {
            get {
                return ResourceManager.GetString("Btn_ClosePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string Btn_Fechar {
            get {
                return ResourceManager.GetString("Btn_Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string Btn_Novo {
            get {
                return ResourceManager.GetString("Btn_Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padronizar.
        /// </summary>
        internal static string Btn_Padronizar {
            get {
                return ResourceManager.GetString("Btn_Padronizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Plano.
        /// </summary>
        internal static string Btn_PlanoAcao {
            get {
                return ResourceManager.GetString("Btn_PlanoAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        internal static string Btn_Proximo {
            get {
                return ResourceManager.GetString("Btn_Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar verificações.
        /// </summary>
        internal static string Btn_VerificacoesAcao {
            get {
                return ResourceManager.GetString("Btn_VerificacoesAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apontar verificação.
        /// </summary>
        internal static string Btn_VerificarAtividade {
            get {
                return ResourceManager.GetString("Btn_VerificarAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Btn_Visualizar {
            get {
                return ResourceManager.GetString("Btn_Visualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O problema foi resolvido?.
        /// </summary>
        internal static string Chk_ProblemaResolvido {
            get {
                return ResourceManager.GetString("Chk_ProblemaResolvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja executar um novo ciclo do PDCA?.
        /// </summary>
        internal static string Cmb_NewCiclo {
            get {
                return ResourceManager.GetString("Cmb_NewCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string FRWBtnClose {
            get {
                return ResourceManager.GetString("FRWBtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string FRWBtnSave {
            get {
                return ResourceManager.GetString("FRWBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloco.
        /// </summary>
        internal static string FRWEntity_Block {
            get {
                return ResourceManager.GetString("FRWEntity_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string FRWEntity_Company {
            get {
                return ResourceManager.GetString("FRWEntity_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        internal static string FRWEntity_CompanyName {
            get {
                return ResourceManager.GetString("FRWEntity_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        internal static string FRWEntity_Component {
            get {
                return ResourceManager.GetString("FRWEntity_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente ID.
        /// </summary>
        internal static string FRWEntity_ComponentNameId {
            get {
                return ResourceManager.GetString("FRWEntity_ComponentNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Acesso.
        /// </summary>
        internal static string FRWEntity_DataAccess {
            get {
                return ResourceManager.GetString("FRWEntity_DataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dados.
        /// </summary>
        internal static string FRWEntity_DataType {
            get {
                return ResourceManager.GetString("FRWEntity_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de atualização.
        /// </summary>
        internal static string FRWEntity_DateUpdated {
            get {
                return ResourceManager.GetString("FRWEntity_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor padrão.
        /// </summary>
        internal static string FRWEntity_DefaultValue {
            get {
                return ResourceManager.GetString("FRWEntity_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string FRWEntity_Description {
            get {
                return ResourceManager.GetString("FRWEntity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string FRWEntity_Email {
            get {
                return ResourceManager.GetString("FRWEntity_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome fantasia.
        /// </summary>
        internal static string FRWEntity_FantasyName {
            get {
                return ResourceManager.GetString("FRWEntity_FantasyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        internal static string FRWEntity_Height {
            get {
                return ResourceManager.GetString("FRWEntity_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string FRWEntity_ID {
            get {
                return ResourceManager.GetString("FRWEntity_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Imagem Menu.
        /// </summary>
        internal static string FRWEntity_ImageUrl {
            get {
                return ResourceManager.GetString("FRWEntity_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Externo.
        /// </summary>
        internal static string FRWEntity_IPv4_External {
            get {
                return ResourceManager.GetString("FRWEntity_IPv4_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Interno.
        /// </summary>
        internal static string FRWEntity_IPv4_Internal {
            get {
                return ResourceManager.GetString("FRWEntity_IPv4_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Externo.
        /// </summary>
        internal static string FRWEntity_IPv6_External {
            get {
                return ResourceManager.GetString("FRWEntity_IPv6_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Interno.
        /// </summary>
        internal static string FRWEntity_IPv6_Internal {
            get {
                return ResourceManager.GetString("FRWEntity_IPv6_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário pode acessar o Sistema?.
        /// </summary>
        internal static string FRWEntity_IsAccessAllowed {
            get {
                return ResourceManager.GetString("FRWEntity_IsAccessAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa obrigatória.
        /// </summary>
        internal static string FRWEntity_IsCompanyRequired {
            get {
                return ResourceManager.GetString("FRWEntity_IsCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa padrão.
        /// </summary>
        internal static string FRWEntity_IsDefaultCompany {
            get {
                return ResourceManager.GetString("FRWEntity_IsDefaultCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editável.
        /// </summary>
        internal static string FRWEntity_IsEditable {
            get {
                return ResourceManager.GetString("FRWEntity_IsEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string FRWEntity_IsEnable {
            get {
                return ResourceManager.GetString("FRWEntity_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite visualizar.
        /// </summary>
        internal static string FRWEntity_IsPreview {
            get {
                return ResourceManager.GetString("FRWEntity_IsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente leitura.
        /// </summary>
        internal static string FRWEntity_IsReadOnly {
            get {
                return ResourceManager.GetString("FRWEntity_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível.
        /// </summary>
        internal static string FRWEntity_IsVisible {
            get {
                return ResourceManager.GetString("FRWEntity_IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave da tabela.
        /// </summary>
        internal static string FRWEntity_KeyDatabase {
            get {
                return ResourceManager.GetString("FRWEntity_KeyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string FRWEntity_Menu {
            get {
                return ResourceManager.GetString("FRWEntity_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Pai.
        /// </summary>
        internal static string FRWEntity_MenuParent {
            get {
                return ResourceManager.GetString("FRWEntity_MenuParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura Mínima.
        /// </summary>
        internal static string FRWEntity_MinHeight {
            get {
                return ResourceManager.GetString("FRWEntity_MinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura Mínima.
        /// </summary>
        internal static string FRWEntity_MinWidth {
            get {
                return ResourceManager.GetString("FRWEntity_MinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro.
        /// </summary>
        internal static string FRWEntity_Param {
            get {
                return ResourceManager.GetString("FRWEntity_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string FRWEntity_Phone {
            get {
                return ResourceManager.GetString("FRWEntity_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string FRWEntity_Profile {
            get {
                return ResourceManager.GetString("FRWEntity_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinir Senha Próximo Login?.
        /// </summary>
        internal static string FRWEntity_RedefinePswdNextLogin {
            get {
                return ResourceManager.GetString("FRWEntity_RedefinePswdNextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressão regular.
        /// </summary>
        internal static string FRWEntity_Regex {
            get {
                return ResourceManager.GetString("FRWEntity_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequência.
        /// </summary>
        internal static string FRWEntity_Sequence {
            get {
                return ResourceManager.GetString("FRWEntity_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID da Seção.
        /// </summary>
        internal static string FRWEntity_SessionID {
            get {
                return ResourceManager.GetString("FRWEntity_SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave de tradução.
        /// </summary>
        internal static string FRWEntity_TranslateKeyName {
            get {
                return ResourceManager.GetString("FRWEntity_TranslateKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do tipo.
        /// </summary>
        internal static string FRWEntity_TypeName {
            get {
                return ResourceManager.GetString("FRWEntity_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string FRWEntity_User {
            get {
                return ResourceManager.GetString("FRWEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        internal static string FRWEntity_UserFullName {
            get {
                return ResourceManager.GetString("FRWEntity_UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string FRWEntity_UserLogin {
            get {
                return ResourceManager.GetString("FRWEntity_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string FRWEntity_UserPassword {
            get {
                return ResourceManager.GetString("FRWEntity_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string FRWEntity_Value {
            get {
                return ResourceManager.GetString("FRWEntity_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura.
        /// </summary>
        internal static string FRWEntity_Width {
            get {
                return ResourceManager.GetString("FRWEntity_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela.
        /// </summary>
        internal static string FRWEntity_Window {
            get {
                return ResourceManager.GetString("FRWEntity_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string FRWEntity_WindowAlias {
            get {
                return ResourceManager.GetString("FRWEntity_WindowAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da Tela.
        /// </summary>
        internal static string FRWEntity_WindowDescription {
            get {
                return ResourceManager.GetString("FRWEntity_WindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerador.
        /// </summary>
        internal static string FRWEntity_WindowEnum {
            get {
                return ResourceManager.GetString("FRWEntity_WindowEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path/URL.
        /// </summary>
        internal static string FRWEntity_WindowPath {
            get {
                return ResourceManager.GetString("FRWEntity_WindowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Tela.
        /// </summary>
        internal static string FRWEntity_WindowTitle {
            get {
                return ResourceManager.GetString("FRWEntity_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título no Menu.
        /// </summary>
        internal static string FRWEntity_WindowTitleMenu {
            get {
                return ResourceManager.GetString("FRWEntity_WindowTitleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você responderá como se deverá realizar esta atividade.
        /// </summary>
        internal static string Help_Acao_ComoFazer {
            get {
                return ResourceManager.GetString("Help_Acao_ComoFazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você determinará a data para finalizar a atividade.
        /// </summary>
        internal static string Help_Acao_DataFim {
            get {
                return ResourceManager.GetString("Help_Acao_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você determinará a data para iniciar a atividade.
        /// </summary>
        internal static string Help_Acao_DataInicio {
            get {
                return ResourceManager.GetString("Help_Acao_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você colocará se esta atividade terá algum impacto, por exemplo: algum custo extra.
        /// </summary>
        internal static string Help_Acao_Impacto {
            get {
                return ResourceManager.GetString("Help_Acao_Impacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você responderá por que a atividade precisa ser executada.
        /// </summary>
        internal static string Help_Acao_Porque {
            get {
                return ResourceManager.GetString("Help_Acao_Porque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você selecionará o responsável para realizar esta atividade.
        /// </summary>
        internal static string Help_Acao_Responsavel {
            get {
                return ResourceManager.GetString("Help_Acao_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você colocará aonde será executada esta atividade.
        /// </summary>
        internal static string Help_Acao_Setor {
            get {
                return ResourceManager.GetString("Help_Acao_Setor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você colocará o título da atividade a realizar.
        /// </summary>
        internal static string Help_Acao_Titulo {
            get {
                return ResourceManager.GetString("Help_Acao_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica a causa do brainstorming.
        /// </summary>
        internal static string Help_Causa_Informativa {
            get {
                return ResourceManager.GetString("Help_Causa_Informativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica a causa raíz.
        /// </summary>
        internal static string Help_CincoPorques_Informativa {
            get {
                return ResourceManager.GetString("Help_CincoPorques_Informativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha a tela.
        /// </summary>
        internal static string Help_Close {
            get {
                return ResourceManager.GetString("Help_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar planejamento. Passar o problema para a etapa de Execução [DO]..
        /// </summary>
        internal static string Help_PlanoAcao_FimPlanejamento {
            get {
                return ResourceManager.GetString("Help_PlanoAcao_FimPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica quantos Ciclos já foram executados para o problema.
        /// </summary>
        internal static string Help_Problema_Ciclo {
            get {
                return ResourceManager.GetString("Help_Problema_Ciclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você colocará as informações que você conhece do problema a resolver.
        /// </summary>
        internal static string Help_Problema_Descricao {
            get {
                return ResourceManager.GetString("Help_Problema_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica o título do problema.
        /// </summary>
        internal static string Help_Problema_DescricaoInformativa {
            get {
                return ResourceManager.GetString("Help_Problema_DescricaoInformativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifica em qual etapa do PDCA seu problema se encontra.
        /// </summary>
        internal static string Help_Problema_Fase {
            get {
                return ResourceManager.GetString("Help_Problema_Fase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você colocará uma Meta que deseja atingir ao final deste Ciclo.
        /// </summary>
        internal static string Help_Problema_Meta {
            get {
                return ResourceManager.GetString("Help_Problema_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avança para a próxima etapa do planejamento.
        /// </summary>
        internal static string Help_Problema_Proximo {
            get {
                return ResourceManager.GetString("Help_Problema_Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui será identificado o responsável deste Ciclo.
        /// </summary>
        internal static string Help_Problema_Responsavel {
            get {
                return ResourceManager.GetString("Help_Problema_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você deve descrever um título resumido que identifique o problema, de forma quantificável.
        /// </summary>
        internal static string Help_Problema_Titulo {
            get {
                return ResourceManager.GetString("Help_Problema_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir uma causa.
        /// </summary>
        internal static string Help_ProblemaCausa_BtnDelete {
            get {
                return ResourceManager.GetString("Help_ProblemaCausa_BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar uma causa.
        /// </summary>
        internal static string Help_ProblemaCausa_BtnEdit {
            get {
                return ResourceManager.GetString("Help_ProblemaCausa_BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar uma causa.
        /// </summary>
        internal static string Help_ProblemaCausa_BtnNew {
            get {
                return ResourceManager.GetString("Help_ProblemaCausa_BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string KPComponents_Delete {
            get {
                return ResourceManager.GetString("KPComponents_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string KPComponents_Edit {
            get {
                return ResourceManager.GetString("KPComponents_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect User or Password!.
        /// </summary>
        internal static string KPComponents_IncorrectUserOrPassword {
            get {
                return ResourceManager.GetString("KPComponents_IncorrectUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir este registro, pois ele já possui relacionamentos!.
        /// </summary>
        internal static string KPComponents_MessageExistsRelations {
            get {
                return ResourceManager.GetString("KPComponents_MessageExistsRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar um valor na tabela..
        /// </summary>
        internal static string KPComponents_MessageSelectTableValue {
            get {
                return ResourceManager.GetString("KPComponents_MessageSelectTableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string KPComponents_New {
            get {
                return ResourceManager.GetString("KPComponents_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o registro?.
        /// </summary>
        internal static string KPComponents_QuestionDeleteReg {
            get {
                return ResourceManager.GetString("KPComponents_QuestionDeleteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Failure..
        /// </summary>
        internal static string KPComponents_SecurityFail {
            get {
                return ResourceManager.GetString("KPComponents_SecurityFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        internal static string KPComponents_Select {
            get {
                return ResourceManager.GetString("KPComponents_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was not found!.
        /// </summary>
        internal static string KPComponents_SessionNotFound {
            get {
                return ResourceManager.GetString("KPComponents_SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was not possible to set the session!.
        /// </summary>
        internal static string KPComponents_SessionNotSet {
            get {
                return ResourceManager.GetString("KPComponents_SessionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session object is not Entity!.
        /// </summary>
        internal static string KPComponents_SessionObjectNotEntity {
            get {
                return ResourceManager.GetString("KPComponents_SessionObjectNotEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string KPEntity_Description {
            get {
                return ResourceManager.GetString("KPEntity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string KPEntity_Login {
            get {
                return ResourceManager.GetString("KPEntity_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        internal static string Label_Acao {
            get {
                return ResourceManager.GetString("Label_Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência.
        /// </summary>
        internal static string Label_Agencia {
            get {
                return ResourceManager.GetString("Label_Agencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        internal static string Label_Apelido {
            get {
                return ResourceManager.GetString("Label_Apelido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string Label_Bairro {
            get {
                return ResourceManager.GetString("Label_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string Label_Cargo {
            get {
                return ResourceManager.GetString("Label_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causa.
        /// </summary>
        internal static string Label_Causa {
            get {
                return ResourceManager.GetString("Label_Causa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string Label_Celular {
            get {
                return ResourceManager.GetString("Label_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string Label_CEP {
            get {
                return ResourceManager.GetString("Label_CEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo.
        /// </summary>
        internal static string Label_Ciclo {
            get {
                return ResourceManager.GetString("Label_Ciclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string Label_Cidade {
            get {
                return ResourceManager.GetString("Label_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinco Porques.
        /// </summary>
        internal static string Label_CincoPorques {
            get {
                return ResourceManager.GetString("Label_CincoPorques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinco Proques Pai.
        /// </summary>
        internal static string Label_CincoProquesPai {
            get {
                return ResourceManager.GetString("Label_CincoProquesPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como Fazer?.
        /// </summary>
        internal static string Label_ComoFazer {
            get {
                return ResourceManager.GetString("Label_ComoFazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string Label_Complemento {
            get {
                return ResourceManager.GetString("Label_Complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Bancária.
        /// </summary>
        internal static string Label_Conta_Bancaria {
            get {
                return ResourceManager.GetString("Label_Conta_Bancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string Label_CPF {
            get {
                return ResourceManager.GetString("Label_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTPS.
        /// </summary>
        internal static string Label_CTPS {
            get {
                return ResourceManager.GetString("Label_CTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Alteração.
        /// </summary>
        internal static string Label_DataAlteracao {
            get {
                return ResourceManager.GetString("Label_DataAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisado em.
        /// </summary>
        internal static string Label_DataAnalise {
            get {
                return ResourceManager.GetString("Label_DataAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Conclusão.
        /// </summary>
        internal static string Label_DataConclusao {
            get {
                return ResourceManager.GetString("Label_DataConclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        internal static string Label_DataFinal {
            get {
                return ResourceManager.GetString("Label_DataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        internal static string Label_DataInicio {
            get {
                return ResourceManager.GetString("Label_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resgistrado em.
        /// </summary>
        internal static string Label_DataRegistro {
            get {
                return ResourceManager.GetString("Label_DataRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Verificação.
        /// </summary>
        internal static string Label_DataVerificacao {
            get {
                return ResourceManager.GetString("Label_DataVerificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Label_Descricao {
            get {
                return ResourceManager.GetString("Label_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Label_Empresa {
            get {
                return ResourceManager.GetString("Label_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string Label_Endereco {
            get {
                return ResourceManager.GetString("Label_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase.
        /// </summary>
        internal static string Label_Fase {
            get {
                return ResourceManager.GetString("Label_Fase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        internal static string Label_Genero {
            get {
                return ResourceManager.GetString("Label_Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilidades.
        /// </summary>
        internal static string Label_Habilidades {
            get {
                return ResourceManager.GetString("Label_Habilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitação.
        /// </summary>
        internal static string Label_Habilitacao {
            get {
                return ResourceManager.GetString("Label_Habilitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imóvel.
        /// </summary>
        internal static string Label_Imovel {
            get {
                return ResourceManager.GetString("Label_Imovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual o impacto?.
        /// </summary>
        internal static string Label_Impacto {
            get {
                return ResourceManager.GetString("Label_Impacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lições Apreendidas.
        /// </summary>
        internal static string Label_LicoesApreendidas {
            get {
                return ResourceManager.GetString("Label_LicoesApreendidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Alteração.
        /// </summary>
        internal static string Label_LoginAlteracao {
            get {
                return ResourceManager.GetString("Label_LoginAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta de Solução.
        /// </summary>
        internal static string Label_MetaSolucao {
            get {
                return ResourceManager.GetString("Label_MetaSolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudanças Realizadas.
        /// </summary>
        internal static string Label_MudancasRealizadas {
            get {
                return ResourceManager.GetString("Label_MudancasRealizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nascimento.
        /// </summary>
        internal static string Label_Nascimento {
            get {
                return ResourceManager.GetString("Label_Nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Label_Nome {
            get {
                return ResourceManager.GetString("Label_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo.
        /// </summary>
        internal static string Label_NomeCompleto {
            get {
                return ResourceManager.GetString("Label_NomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Ciclo.
        /// </summary>
        internal static string Label_NovoCiclo {
            get {
                return ResourceManager.GetString("Label_NovoCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerado novo ciclo?.
        /// </summary>
        internal static string Label_NovoCicloGerado {
            get {
                return ResourceManager.GetString("Label_NovoCicloGerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string Label_Numero {
            get {
                return ResourceManager.GetString("Label_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string Label_Observacao {
            get {
                return ResourceManager.GetString("Label_Observacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Concl..
        /// </summary>
        internal static string Label_PercentConclusao {
            get {
                return ResourceManager.GetString("Label_PercentConclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % de conclusão.
        /// </summary>
        internal static string Label_PercentDeConclusao {
            get {
                return ResourceManager.GetString("Label_PercentDeConclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual de Conclusão.
        /// </summary>
        internal static string Label_Percentual {
            get {
                return ResourceManager.GetString("Label_Percentual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS.
        /// </summary>
        internal static string Label_PIS {
            get {
                return ResourceManager.GetString("Label_PIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por quê?.
        /// </summary>
        internal static string Label_Porque {
            get {
                return ResourceManager.GetString("Label_Porque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema.
        /// </summary>
        internal static string Label_Problema {
            get {
                return ResourceManager.GetString("Label_Problema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema Resolvido.
        /// </summary>
        internal static string Label_ProblemaResolvido {
            get {
                return ResourceManager.GetString("Label_ProblemaResolvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        internal static string Label_Radio {
            get {
                return ResourceManager.GetString("Label_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro CNH.
        /// </summary>
        internal static string Label_Registro_CNH {
            get {
                return ResourceManager.GetString("Label_Registro_CNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder.
        /// </summary>
        internal static string Label_Responder {
            get {
                return ResourceManager.GetString("Label_Responder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string Label_Responsavel {
            get {
                return ResourceManager.GetString("Label_Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta.
        /// </summary>
        internal static string Label_Resposta {
            get {
                return ResourceManager.GetString("Label_Resposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        internal static string Label_RG {
            get {
                return ResourceManager.GetString("Label_RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        internal static string Label_Serie {
            get {
                return ResourceManager.GetString("Label_Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aonde?.
        /// </summary>
        internal static string Label_Setor {
            get {
                return ResourceManager.GetString("Label_Setor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string Label_Skype {
            get {
                return ResourceManager.GetString("Label_Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string Label_Telefone {
            get {
                return ResourceManager.GetString("Label_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Imóvel.
        /// </summary>
        internal static string Label_Tipo_Imovel {
            get {
                return ResourceManager.GetString("Label_Tipo_Imovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gráfico.
        /// </summary>
        internal static string Label_TipoGrafico {
            get {
                return ResourceManager.GetString("Label_TipoGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Label_TipoTicket {
            get {
                return ResourceManager.GetString("Label_TipoTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Label_Titulo {
            get {
                return ResourceManager.GetString("Label_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título Ação.
        /// </summary>
        internal static string Label_TituloAcao {
            get {
                return ResourceManager.GetString("Label_TituloAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do Gráfico.
        /// </summary>
        internal static string Label_TituloGrafico {
            get {
                return ResourceManager.GetString("Label_TituloGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        internal static string Label_UF {
            get {
                return ResourceManager.GetString("Label_UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF Hab..
        /// </summary>
        internal static string Label_UF_Habilitacao {
            get {
                return ResourceManager.GetString("Label_UF_Habilitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string Label_Usuario {
            get {
                return ResourceManager.GetString("Label_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este Login já esta cadastrado!.
        /// </summary>
        internal static string Message_ValidateExistLogin {
            get {
                return ResourceManager.GetString("Message_ValidateExistLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login não pode conter caracteres de espaço!.
        /// </summary>
        internal static string Message_ValidateLoginEmpty {
            get {
                return ResourceManager.GetString("Message_ValidateLoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string Translate_ButtonAdd {
            get {
                return ResourceManager.GetString("Translate_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar Usuários.
        /// </summary>
        internal static string Translate_ButtonUserRelationship {
            get {
                return ResourceManager.GetString("Translate_ButtonUserRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Translate_ButtonView {
            get {
                return ResourceManager.GetString("Translate_ButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacionar Telas.
        /// </summary>
        internal static string Translate_ButtonWindowRelationship {
            get {
                return ResourceManager.GetString("Translate_ButtonWindowRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string Translate_Dashboard {
            get {
                return ResourceManager.GetString("Translate_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string Translate_User {
            get {
                return ResourceManager.GetString("Translate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um causa.
        /// </summary>
        internal static string Translate_ZoomCausa {
            get {
                return ResourceManager.GetString("Translate_ZoomCausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma empresa.
        /// </summary>
        internal static string Translate_ZoomCompany {
            get {
                return ResourceManager.GetString("Translate_ZoomCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um menu.
        /// </summary>
        internal static string Translate_ZoomMenu {
            get {
                return ResourceManager.GetString("Translate_ZoomMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um problema.
        /// </summary>
        internal static string Translate_ZoomProblema {
            get {
                return ResourceManager.GetString("Translate_ZoomProblema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um responsável.
        /// </summary>
        internal static string Translate_ZoomResponsavel {
            get {
                return ResourceManager.GetString("Translate_ZoomResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um item.
        /// </summary>
        internal static string Translate_ZoomSelectItem {
            get {
                return ResourceManager.GetString("Translate_ZoomSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um ciclo.
        /// </summary>
        internal static string Translate_ZoomWindowCiclo {
            get {
                return ResourceManager.GetString("Translate_ZoomWindowCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um usuário.
        /// </summary>
        internal static string Translate_ZoomWindowTitleUser {
            get {
                return ResourceManager.GetString("Translate_ZoomWindowTitleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma tela.
        /// </summary>
        internal static string Translate_ZoomWindowTitleWindow {
            get {
                return ResourceManager.GetString("Translate_ZoomWindowTitleWindow", resourceCulture);
            }
        }
    }
}
